---
title: "Oxygen, Salinity, and pH"
author: "Connor Flynn"
date: "11/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse,
                here,
                janitor,
                lubridate,
                plotly,
                RColorBrewer,
                estimatr, 
                gridExtra)

```


Read in Data

```{r}
dissolved_oxygen_data <- read_csv(here("dissolved_oxygen_kalauhaihai_oct_nov_2022.csv"))

pH_data <- read_csv(here("pH_kalauhaihai_oct_nov_2022.csv"))

conductivity_data <- read_csv(here("conductivity_kalauhaihai_oct_nov_2022.csv"))
```

Merge Date and Time Columns 

```{r}
dissolved_oxygen_data$Date_Time = dmy_hms(paste(dissolved_oxygen_data$Date, dissolved_oxygen_data$Time))

pH_data$Date_Time = dmy_hms(paste(pH_data$Date, pH_data$Time))

conductivity_data$Date_Time = dmy_hms(paste(conductivity_data$Date, conductivity_data$Time))
```

Plot Data

```{r}
do_plot <- ggplot(data = dissolved_oxygen_data, aes(x = Date_Time, y = Dissolved_Oxygen_Concentration)) + 
  geom_line(color="#619CFF") +
  theme_minimal() 
do_plot
```


```{r}
ggplotly(do_plot)
```

```{r}
do_plot_Temp <- ggplot(data = dissolved_oxygen_data, aes(x = Date_Time, y = Temp)) + 
  geom_line(color="#619CFF") +
  theme_minimal() 

ggplotly(do_plot_Temp)
```




```{r}
pH_plot <- ggplot(data = pH_data, aes(x = Date_Time, y = pH)) + 
  geom_line(color = "#F8766D") +
  theme_minimal()

ggplotly(pH_plot)
  
```

```{r}
pH_plot_Temp <- ggplot(data = pH_data, aes(x = Date_Time, y = Temp)) + 
  geom_line(color = "#F8766D") +
  theme_minimal()

ggplotly(pH_plot_Temp)
```


```{r}
ggplot(data = pH_data, aes(x = Temp, y = pH)) +
  geom_point(color = "#619CFF") +
  geom_smooth(method = lm, color = "#F8766D",se=FALSE,fullrange=TRUE) +
  theme_minimal()
```



```{r}
conductivity_plot <- ggplot(data = conductivity_data, aes(x = Date_Time, y = High_Range_micro_siemens_per_centimeter)) + 
  geom_line(color = "#00BA38") +
  theme_minimal()
ggplotly(conductivity_plot)
```

```{r}
conductivity_plot_Temp <- ggplot(data = conductivity_data, aes(x = Date_Time, y = Temp_Celcius)) + 
  geom_line(color = "#00BA38") +
  theme_minimal()

ggplotly(conductivity_plot_Temp)
```



```{r}
grid.arrange(conductivity_plot, conductivity_plot_Temp, pH_plot, do_plot)
```



Merge pH and Dissolved Oxygen

```{r}
pH_dissolved_oxygen_data <- left_join(pH_data, dissolved_oxygen_data, by = "Date_Time" )
```


Plot Relationship between pH and dissolved oxygen

```{r}
ggplot(data = pH_dissolved_oxygen_data, aes(x = pH, y = Dissolved_Oxygen_Concentration)) +
  geom_point(color = "#619CFF") +
  geom_smooth(method = lm, color = "#F8766D",se=FALSE,fullrange=TRUE) +
  theme_minimal()
```

Regression Formula

```{r}
lm_robust(data = pH_dissolved_oxygen_data, pH ~ Dissolved_Oxygen_Concentration)
```


```{r}
pH_dissolved_oxygen_conductivity_data <- left_join(pH_dissolved_oxygen_data, conductivity_data, by = "Date_Time" )
```


```{r}
pH_dissolved_oxygen_conductivity_data_longer <- pH_dissolved_oxygen_conductivity_data %>% 
  pivot_longer(cols = c(Low_Range_micro_siemens_per_centimeter, High_Range_micro_siemens_per_centimeter, Temp_Celcius, Dissolved_Oxygen_Concentration, pH), names_to = "measurement", values_to = "value")
```


```{r}
ggplot(data = pH_dissolved_oxygen_conductivity_data_longer, aes(x = Date_Time, y = value)) +
  geom_line() +
  facet_wrap(~measurement)
```

